version: "3.7"

services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/db/postgres:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3.8.9-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./data/db/rabbitmq:/var/lib/rabbitmq  